---
title: "081 School map example"
author: "Chin-Cheng Liang"
date: "10/7/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```


```{r}
library(readr)
library(dplyr)
library(ggmap)
library(leaflet)
```

```{r warning=F}
school_latlon <- read_csv("data-committed/07_schools/03_school_latlon.csv") %>% rename(student_samples = nn)
```


# 靜態地圖可用 ggmap 製作

```{r}
school_latlon %>% qmplot(
    lon,
    lat,
    data = .,
    color = level,
    alpha = .3,
    size = student_samples
    ) + guides(alpha = FALSE)
```

```{r}
pal <- colorFactor(c( "red", "green", "blue"), domain = c("elementary", "junior", "senior"))

school_latlon %>%
    mutate(label = paste(user_school, student_samples, "students")) %>%
    leaflet() %>%
    addProviderTiles(providers$CartoDB.Positron) %>%
    addCircleMarkers(
    ~ lon,
    ~ lat,
    color = ~ pal(level),
    label = ~ label,
    stroke = FALSE,
    radius =  ~ log(student_samples),
    fillOpacity = 0.5
    ) %>%
    addLegend(pal = pal, values = ~level)
```

